name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"           # ירוץ אם ה-Dockerfile משתנה
      - "index.html"           # ירוץ אם index.html משתנה
      - ".github/workflows/**" # ירוץ אם ה-Workflow עצמו משתנה
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "index.html"
      - ".github/workflows/**"

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # שלב 1: בדיקה של הקוד מתוך ה-Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # שלב 2: התחברות ל-ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.accesskeyid }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.secretkey }}
          AWS_REGION: il-central-1

      # שלב 3: בניית Docker Image
      - name: Build Docker image
        run: |
 feature/new-branch
          docker build -t 686255965392.dkr.ecr.il-central-1.amazonaws.com/calculator-app:1.1 .

          docker build -t 686255965392.dkr.ecr.il-central-1.amazonaws.com/calculator-app:1.1 .
 

      # שלב 4: דחיפת Docker Image ל-ECR
      - name: Push Docker image to Amazon ECR
        run: |
 feature/new-branch
          docker tag 686255965392.dkr.ecr.il-central-1.amazonaws.com/calculator-app:1.1 686255965392.dkr.ecr.il-central-1.amazonaws.com/calculator-app:1.1
          docker push 686255965392.dkr.ecr.il-central-1.amazonaws.com/calculator-app:1.1

          docker tag 686255965392.dkr.ecr.il-central-1.amazonaws.com/calculator-app:1.1 686255965392.dkr.ecr.il-central-1.amazonaws.com/calculator-app:1.1
          docker push 686255965392.dkr.ecr.il-central-1.amazonaws.com/calculator-app:1.1
 
